@echo off
cd /d %~dp0
echo 🔋 启动蚂蚁军团生存任务...
python queen.py
echo 🕵️ 正在执行猎火侦察...
python firehunter.py
echo 🌱 正在生成复刻方案...
python gasplanter.py
echo 🎩 正在运行 AI 取名引擎（示例）...
python name_generator.py
echo 📊 正在生成可视化报告...
python dashboard.py
echo ✅ 今日任务全部完成！
pause
